/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.librairy.service.nlp.facade.model;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Annotation extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Annotation\",\"namespace\":\"org.librairy.service.nlp.facade.model\",\"fields\":[{\"name\":\"target\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"value\",\"type\":{\"type\":\"map\",\"values\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
   private java.lang.String target;
   private java.util.Map<java.lang.String,java.lang.String> value;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Annotation() {}

  /**
   * All-args constructor.
   */
  public Annotation(java.lang.String target, java.util.Map<java.lang.String,java.lang.String> value) {
    this.target = target;
    this.value = value;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return target;
    case 1: return value;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: target = (java.lang.String)value$; break;
    case 1: value = (java.util.Map<java.lang.String,java.lang.String>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'target' field.
   */
  public java.lang.String getTarget() {
    return target;
  }

  /**
   * Sets the value of the 'target' field.
   * @param value the value to set.
   */
  public void setTarget(java.lang.String value) {
    this.target = value;
  }

  /**
   * Gets the value of the 'value' field.
   */
  public java.util.Map<java.lang.String,java.lang.String> getValue() {
    return value;
  }

  /**
   * Sets the value of the 'value' field.
   * @param value the value to set.
   */
  public void setValue(java.util.Map<java.lang.String,java.lang.String> value) {
    this.value = value;
  }

  /** Creates a new Annotation RecordBuilder */
  public static org.librairy.service.nlp.facade.model.Annotation.Builder newBuilder() {
    return new org.librairy.service.nlp.facade.model.Annotation.Builder();
  }
  
  /** Creates a new Annotation RecordBuilder by copying an existing Builder */
  public static org.librairy.service.nlp.facade.model.Annotation.Builder newBuilder(org.librairy.service.nlp.facade.model.Annotation.Builder other) {
    return new org.librairy.service.nlp.facade.model.Annotation.Builder(other);
  }
  
  /** Creates a new Annotation RecordBuilder by copying an existing Annotation instance */
  public static org.librairy.service.nlp.facade.model.Annotation.Builder newBuilder(org.librairy.service.nlp.facade.model.Annotation other) {
    return new org.librairy.service.nlp.facade.model.Annotation.Builder(other);
  }
  
  /**
   * RecordBuilder for Annotation instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Annotation>
    implements org.apache.avro.data.RecordBuilder<Annotation> {

    private java.lang.String target;
    private java.util.Map<java.lang.String,java.lang.String> value;

    /** Creates a new Builder */
    private Builder() {
      super(org.librairy.service.nlp.facade.model.Annotation.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.librairy.service.nlp.facade.model.Annotation.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.target)) {
        this.target = data().deepCopy(fields()[0].schema(), other.target);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.value)) {
        this.value = data().deepCopy(fields()[1].schema(), other.value);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Annotation instance */
    private Builder(org.librairy.service.nlp.facade.model.Annotation other) {
            super(org.librairy.service.nlp.facade.model.Annotation.SCHEMA$);
      if (isValidValue(fields()[0], other.target)) {
        this.target = data().deepCopy(fields()[0].schema(), other.target);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.value)) {
        this.value = data().deepCopy(fields()[1].schema(), other.value);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'target' field */
    public java.lang.String getTarget() {
      return target;
    }
    
    /** Sets the value of the 'target' field */
    public org.librairy.service.nlp.facade.model.Annotation.Builder setTarget(java.lang.String value) {
      validate(fields()[0], value);
      this.target = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'target' field has been set */
    public boolean hasTarget() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'target' field */
    public org.librairy.service.nlp.facade.model.Annotation.Builder clearTarget() {
      target = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'value' field */
    public java.util.Map<java.lang.String,java.lang.String> getValue() {
      return value;
    }
    
    /** Sets the value of the 'value' field */
    public org.librairy.service.nlp.facade.model.Annotation.Builder setValue(java.util.Map<java.lang.String,java.lang.String> value) {
      validate(fields()[1], value);
      this.value = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'value' field has been set */
    public boolean hasValue() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'value' field */
    public org.librairy.service.nlp.facade.model.Annotation.Builder clearValue() {
      value = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public Annotation build() {
      try {
        Annotation record = new Annotation();
        record.target = fieldSetFlags()[0] ? this.target : (java.lang.String) defaultValue(fields()[0]);
        record.value = fieldSetFlags()[1] ? this.value : (java.util.Map<java.lang.String,java.lang.String>) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
