/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.librairy.service.nlp.facade.model;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Form {
  RAW, LEMMA, STEM  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Form\",\"namespace\":\"org.librairy.service.nlp.facade.model\",\"symbols\":[\"RAW\",\"LEMMA\",\"STEM\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
