/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.librairy.service.nlp.facade.model;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Group extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Group\",\"namespace\":\"org.librairy.service.nlp.facade.model\",\"fields\":[{\"name\":\"token\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"pos\",\"type\":{\"type\":\"enum\",\"name\":\"PoS\",\"symbols\":[\"NOUN\",\"PROPER_NOUN\",\"VERB\",\"ADJECTIVE\",\"ADVERB\",\"PRONOUN\",\"PREPOSITION\",\"CONJUNCTION\",\"INTERJECTION\",\"ARTICLE\",\"PUNCTUATION_MARK\",\"NUMBER\",\"DATE\",\"SYMBOL\"]},\"order\":\"ignore\"},{\"name\":\"synsets\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},\"default\":[],\"order\":\"ignore\"},{\"name\":\"uri\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null,\"order\":\"ignore\"},{\"name\":\"freq\",\"type\":\"long\",\"order\":\"ignore\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
   private java.lang.String token;
   private org.librairy.service.nlp.facade.model.PoS pos;
   private java.util.List<java.lang.String> synsets;
   private java.lang.String uri;
   private long freq;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Group() {}

  /**
   * All-args constructor.
   */
  public Group(java.lang.String token, org.librairy.service.nlp.facade.model.PoS pos, java.util.List<java.lang.String> synsets, java.lang.String uri, java.lang.Long freq) {
    this.token = token;
    this.pos = pos;
    this.synsets = synsets;
    this.uri = uri;
    this.freq = freq;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return token;
    case 1: return pos;
    case 2: return synsets;
    case 3: return uri;
    case 4: return freq;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: token = (java.lang.String)value$; break;
    case 1: pos = (org.librairy.service.nlp.facade.model.PoS)value$; break;
    case 2: synsets = (java.util.List<java.lang.String>)value$; break;
    case 3: uri = (java.lang.String)value$; break;
    case 4: freq = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'token' field.
   */
  public java.lang.String getToken() {
    return token;
  }

  /**
   * Sets the value of the 'token' field.
   * @param value the value to set.
   */
  public void setToken(java.lang.String value) {
    this.token = value;
  }

  /**
   * Gets the value of the 'pos' field.
   */
  public org.librairy.service.nlp.facade.model.PoS getPos() {
    return pos;
  }

  /**
   * Sets the value of the 'pos' field.
   * @param value the value to set.
   */
  public void setPos(org.librairy.service.nlp.facade.model.PoS value) {
    this.pos = value;
  }

  /**
   * Gets the value of the 'synsets' field.
   */
  public java.util.List<java.lang.String> getSynsets() {
    return synsets;
  }

  /**
   * Sets the value of the 'synsets' field.
   * @param value the value to set.
   */
  public void setSynsets(java.util.List<java.lang.String> value) {
    this.synsets = value;
  }

  /**
   * Gets the value of the 'uri' field.
   */
  public java.lang.String getUri() {
    return uri;
  }

  /**
   * Sets the value of the 'uri' field.
   * @param value the value to set.
   */
  public void setUri(java.lang.String value) {
    this.uri = value;
  }

  /**
   * Gets the value of the 'freq' field.
   */
  public java.lang.Long getFreq() {
    return freq;
  }

  /**
   * Sets the value of the 'freq' field.
   * @param value the value to set.
   */
  public void setFreq(java.lang.Long value) {
    this.freq = value;
  }

  /** Creates a new Group RecordBuilder */
  public static org.librairy.service.nlp.facade.model.Group.Builder newBuilder() {
    return new org.librairy.service.nlp.facade.model.Group.Builder();
  }
  
  /** Creates a new Group RecordBuilder by copying an existing Builder */
  public static org.librairy.service.nlp.facade.model.Group.Builder newBuilder(org.librairy.service.nlp.facade.model.Group.Builder other) {
    return new org.librairy.service.nlp.facade.model.Group.Builder(other);
  }
  
  /** Creates a new Group RecordBuilder by copying an existing Group instance */
  public static org.librairy.service.nlp.facade.model.Group.Builder newBuilder(org.librairy.service.nlp.facade.model.Group other) {
    return new org.librairy.service.nlp.facade.model.Group.Builder(other);
  }
  
  /**
   * RecordBuilder for Group instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Group>
    implements org.apache.avro.data.RecordBuilder<Group> {

    private java.lang.String token;
    private org.librairy.service.nlp.facade.model.PoS pos;
    private java.util.List<java.lang.String> synsets;
    private java.lang.String uri;
    private long freq;

    /** Creates a new Builder */
    private Builder() {
      super(org.librairy.service.nlp.facade.model.Group.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.librairy.service.nlp.facade.model.Group.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.token)) {
        this.token = data().deepCopy(fields()[0].schema(), other.token);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.pos)) {
        this.pos = data().deepCopy(fields()[1].schema(), other.pos);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.synsets)) {
        this.synsets = data().deepCopy(fields()[2].schema(), other.synsets);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.uri)) {
        this.uri = data().deepCopy(fields()[3].schema(), other.uri);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.freq)) {
        this.freq = data().deepCopy(fields()[4].schema(), other.freq);
        fieldSetFlags()[4] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Group instance */
    private Builder(org.librairy.service.nlp.facade.model.Group other) {
            super(org.librairy.service.nlp.facade.model.Group.SCHEMA$);
      if (isValidValue(fields()[0], other.token)) {
        this.token = data().deepCopy(fields()[0].schema(), other.token);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.pos)) {
        this.pos = data().deepCopy(fields()[1].schema(), other.pos);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.synsets)) {
        this.synsets = data().deepCopy(fields()[2].schema(), other.synsets);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.uri)) {
        this.uri = data().deepCopy(fields()[3].schema(), other.uri);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.freq)) {
        this.freq = data().deepCopy(fields()[4].schema(), other.freq);
        fieldSetFlags()[4] = true;
      }
    }

    /** Gets the value of the 'token' field */
    public java.lang.String getToken() {
      return token;
    }
    
    /** Sets the value of the 'token' field */
    public org.librairy.service.nlp.facade.model.Group.Builder setToken(java.lang.String value) {
      validate(fields()[0], value);
      this.token = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'token' field has been set */
    public boolean hasToken() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'token' field */
    public org.librairy.service.nlp.facade.model.Group.Builder clearToken() {
      token = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'pos' field */
    public org.librairy.service.nlp.facade.model.PoS getPos() {
      return pos;
    }
    
    /** Sets the value of the 'pos' field */
    public org.librairy.service.nlp.facade.model.Group.Builder setPos(org.librairy.service.nlp.facade.model.PoS value) {
      validate(fields()[1], value);
      this.pos = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'pos' field has been set */
    public boolean hasPos() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'pos' field */
    public org.librairy.service.nlp.facade.model.Group.Builder clearPos() {
      pos = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'synsets' field */
    public java.util.List<java.lang.String> getSynsets() {
      return synsets;
    }
    
    /** Sets the value of the 'synsets' field */
    public org.librairy.service.nlp.facade.model.Group.Builder setSynsets(java.util.List<java.lang.String> value) {
      validate(fields()[2], value);
      this.synsets = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'synsets' field has been set */
    public boolean hasSynsets() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'synsets' field */
    public org.librairy.service.nlp.facade.model.Group.Builder clearSynsets() {
      synsets = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'uri' field */
    public java.lang.String getUri() {
      return uri;
    }
    
    /** Sets the value of the 'uri' field */
    public org.librairy.service.nlp.facade.model.Group.Builder setUri(java.lang.String value) {
      validate(fields()[3], value);
      this.uri = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'uri' field has been set */
    public boolean hasUri() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'uri' field */
    public org.librairy.service.nlp.facade.model.Group.Builder clearUri() {
      uri = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'freq' field */
    public java.lang.Long getFreq() {
      return freq;
    }
    
    /** Sets the value of the 'freq' field */
    public org.librairy.service.nlp.facade.model.Group.Builder setFreq(long value) {
      validate(fields()[4], value);
      this.freq = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'freq' field has been set */
    public boolean hasFreq() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'freq' field */
    public org.librairy.service.nlp.facade.model.Group.Builder clearFreq() {
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    public Group build() {
      try {
        Group record = new Group();
        record.token = fieldSetFlags()[0] ? this.token : (java.lang.String) defaultValue(fields()[0]);
        record.pos = fieldSetFlags()[1] ? this.pos : (org.librairy.service.nlp.facade.model.PoS) defaultValue(fields()[1]);
        record.synsets = fieldSetFlags()[2] ? this.synsets : (java.util.List<java.lang.String>) defaultValue(fields()[2]);
        record.uri = fieldSetFlags()[3] ? this.uri : (java.lang.String) defaultValue(fields()[3]);
        record.freq = fieldSetFlags()[4] ? this.freq : (java.lang.Long) defaultValue(fields()[4]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
