/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.librairy.service.nlp.facade.model;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface NlpService {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"NlpService\",\"namespace\":\"org.librairy.service.nlp.facade.model\",\"types\":[{\"type\":\"enum\",\"name\":\"PoS\",\"symbols\":[\"NOUN\",\"VERB\",\"ADJECTIVE\",\"ADVERB\",\"PRONOUN\",\"PREPOSITION\",\"CONJUNCTION\",\"INTERJECTION\",\"ARTICLE\"]},{\"type\":\"enum\",\"name\":\"Form\",\"symbols\":[\"RAW\",\"LEMMA\",\"STEM\"]},{\"type\":\"record\",\"name\":\"Annotation\",\"fields\":[{\"name\":\"target\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"form\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"termcase\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"lemma\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"morphoFeat\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"pos\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"type\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"sentiment\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"offset\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"para\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}],\"messages\":{\"process\":{\"request\":[{\"name\":\"text\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"filter\",\"type\":{\"type\":\"array\",\"items\":\"PoS\"}},{\"name\":\"form\",\"type\":\"Form\"}],\"response\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},\"annotate\":{\"request\":[{\"name\":\"text\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"filter\",\"type\":{\"type\":\"array\",\"items\":\"PoS\"}}],\"response\":{\"type\":\"array\",\"items\":\"Annotation\"}}}}");
  java.lang.String process(java.lang.String text, java.util.List<org.librairy.service.nlp.facade.model.PoS> filter, org.librairy.service.nlp.facade.model.Form form) throws org.apache.avro.AvroRemoteException;
  java.util.List<org.librairy.service.nlp.facade.model.Annotation> annotate(java.lang.String text, java.util.List<org.librairy.service.nlp.facade.model.PoS> filter) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends NlpService {
    public static final org.apache.avro.Protocol PROTOCOL = org.librairy.service.nlp.facade.model.NlpService.PROTOCOL;
    void process(java.lang.String text, java.util.List<org.librairy.service.nlp.facade.model.PoS> filter, org.librairy.service.nlp.facade.model.Form form, org.apache.avro.ipc.Callback<java.lang.String> callback) throws java.io.IOException;
    void annotate(java.lang.String text, java.util.List<org.librairy.service.nlp.facade.model.PoS> filter, org.apache.avro.ipc.Callback<java.util.List<org.librairy.service.nlp.facade.model.Annotation>> callback) throws java.io.IOException;
  }
}